import http from 'node:http';
import type { Socket } from 'node:net';
import { setSetting } from '../settings';
import { KEY, dashboardBase, localUrl, mobileConfig, normaliseHttpsUrl } from './config';
import type { MobileConfigPatch } from './config';
import {
  ensureMobileToken,
  generateToken,
  generateTopic,
  mobileCredentialsReady,
  mobileSecrets,
  pairingCode,
  persistSecrets,
  secretsIssue,
  topicLooksStrong,
} from './secrets';
import { handle } from './dispatch';
import { safeString } from './snapshot';
import { lastMobilePushResult } from './push';
import type { MobileMonitorConfig, MobileMonitorStatus } from '../../shared/types';
// Routes register themselves at import time. The lifecycle module names every
// route module explicitly rather than trusting the facade's re-exports, so a
// listener can never come up with an empty route table.
import './control';
import './launch-options';
import './git';
import './explore';
import './manage';
import './manage-runs';
import './goals';
import './learning';
import './scout';
import './skills';

/**
 * The listener's lifecycle. It intentionally binds to loopback: reach it from
 * a phone through an operator-owned private reverse proxy (for example
 * Tailscale Serve), not by turning Wanigan into a server on every network the
 * laptop joins. The fixed port makes that proxy stable; the fragment token
 * keeps the credential out of HTTP request logs and Referer headers.
 */

let server: http.Server | null = null;
let serverPort: number | null = null;
let pendingServer: http.Server | null = null;
let starting: Promise<void> | null = null;
let lifecycleVersion = 0;
let lastServerError: string | null = null;
const sockets = new Set<Socket>();

/** Current lifecycle state. The pairing URL is intended for Wanigan's trusted renderer. */
export function mobileStatus(): MobileMonitorStatus {
  const config = mobileConfig();
  const token = ensureMobileToken();
  const push = lastMobilePushResult();
  const credentialIssue = config.dashboardEnabled || config.pushEnabled ? secretsIssue() : null;
  return {
    config,
    running: Boolean(server?.listening && serverPort === config.port),
    localUrl: localUrl(config.port),
    pairingUrl: `${dashboardBase(config)}#token=${encodeURIComponent(token)}`,
    pairingCode: pairingCode(token),
    tokenFingerprint: `${token.slice(0, 8)}…${token.slice(-4)}`,
    error: credentialIssue ?? lastServerError,
    lastPushAt: push?.ok ? push.at : null,
    lastPushError: push && !push.skipped ? push.error : null,
  };
}

/** Persist a validated patch and immediately reconcile the listener. */
export async function setMobileConfig(patch: MobileConfigPatch): Promise<MobileMonitorStatus> {
  const current = mobileConfig();
  const next: MobileMonitorConfig = {
    dashboardEnabled: patch.dashboardEnabled ?? current.dashboardEnabled,
    remoteControlEnabled: patch.remoteControlEnabled ?? current.remoteControlEnabled,
    port: patch.port ?? current.port,
    dashboardUrl: patch.dashboardUrl === undefined
      ? current.dashboardUrl
      : normaliseHttpsUrl(patch.dashboardUrl, 'Dashboard URL'),
    pushEnabled: patch.pushEnabled ?? current.pushEnabled,
    pushServer: patch.pushServer === undefined
      ? current.pushServer
      : normaliseHttpsUrl(patch.pushServer, 'ntfy server'),
    pushTopic: patch.pushTopic ?? current.pushTopic,
  };

  if (!Number.isInteger(next.port) || next.port < 1_024 || next.port > 65_535) {
    throw new Error('Mobile monitor port must be a whole number from 1024 through 65535.');
  }
  if (!topicLooksStrong(next.pushTopic)) {
    throw new Error('The ntfy topic must be the high-entropy topic generated by Wanigan.');
  }
  if (next.pushEnabled && !next.pushServer) {
    throw new Error('Set an HTTPS ntfy server before enabling mobile push.');
  }
  if ((next.dashboardEnabled || next.pushEnabled) && !mobileCredentialsReady()) {
    throw new Error(
      `${secretsIssue() ?? 'Encrypted phone-monitor credentials are unavailable.'} `
      + 'Restore the system keychain or replace the affected credential before turning phone monitoring on.',
    );
  }

  // Persist a changed secret before the non-secret flags. A failed keychain or
  // disk write then leaves the whole previously working configuration intact.
  if (next.pushTopic !== current.pushTopic) {
    const secrets = mobileSecrets();
    persistSecrets({ ...secrets, topic: next.pushTopic });
  }

  // Validate every field before writing any of them, so a rejected patch does
  // not leave half of a configuration behind.
  setSetting(KEY.dashboardEnabled, next.dashboardEnabled ? '1' : '0');
  setSetting(KEY.remoteControlEnabled, next.remoteControlEnabled ? '1' : '0');
  setSetting(KEY.port, String(next.port));
  setSetting(KEY.dashboardUrl, next.dashboardUrl);
  setSetting(KEY.pushEnabled, next.pushEnabled ? '1' : '0');
  setSetting(KEY.pushServer, next.pushServer);
  if (!next.dashboardEnabled || (server && serverPort !== next.port)) stopMobileMonitor();
  return startMobileMonitor();
}

/** Rotate dashboard access immediately; an old fragment/token stops working. */
export async function regenerateMobileToken(): Promise<MobileMonitorStatus> {
  const secrets = mobileSecrets();
  persistSecrets({ ...secrets, token: generateToken() });
  // Credential replacement is also the recovery path for an enabled listener
  // that was paused because the encrypted blob could not be read at startup.
  return startMobileMonitor();
}

/** Rotate the secret ntfy topic independently of dashboard access. */
export async function regenerateMobilePushTopic(): Promise<MobileMonitorStatus> {
  const secrets = mobileSecrets();
  persistSecrets({ ...secrets, topic: generateTopic() });
  return startMobileMonitor();
}

function closeServer(target: http.Server | null): void {
  if (!target) return;
  try { target.closeAllConnections(); } catch { /* older Node or already closed */ }
  try { target.close(); } catch { /* never reached listen */ }
}

/** Start the fixed-port loopback dashboard when its opt-in setting is on. */
export async function startMobileMonitor(): Promise<MobileMonitorStatus> {
  const config = mobileConfig();
  if (!config.dashboardEnabled) {
    stopMobileMonitor();
    lastServerError = null;
    return mobileStatus();
  }
  if (!mobileCredentialsReady()) {
    stopMobileMonitor();
    lastServerError = secretsIssue()
      ?? 'Encrypted phone-monitor credentials are unavailable, so the listener was not started.';
    return mobileStatus();
  }

  if (server?.listening && serverPort === config.port) {
    lastServerError = null;
    return mobileStatus();
  }

  if (starting) {
    await starting.catch(() => {});
    if (server?.listening && serverPort === config.port) return mobileStatus();
  }

  stopMobileMonitor();
  const version = ++lifecycleVersion;
  const candidate = http.createServer((req, res) => { void handle(req, res); });
  pendingServer = candidate;
  candidate.keepAliveTimeout = 2_000;
  candidate.headersTimeout = 5_000;
  candidate.requestTimeout = 5_000;
  candidate.maxHeadersCount = 32;
  candidate.on('connection', (socket: Socket) => {
    sockets.add(socket);
    socket.on('close', () => sockets.delete(socket));
  });

  const task = new Promise<void>((resolve, reject) => {
    const onError = (error: NodeJS.ErrnoException) => {
      reject(new Error(
        error.code === 'EADDRINUSE'
          ? `Port ${config.port} is already in use. Choose another mobile monitor port.`
          : `The mobile monitor could not bind 127.0.0.1:${config.port}: ${error.message}`
      ));
    };
    candidate.once('error', onError);
    candidate.listen(config.port, '127.0.0.1', () => {
      candidate.off('error', onError);
      resolve();
    });
  });
  starting = task;

  try {
    await task;
    if (version !== lifecycleVersion || !mobileConfig().dashboardEnabled) {
      closeServer(candidate);
    } else {
      server = candidate;
      serverPort = config.port;
      pendingServer = null;
      lastServerError = null;
      // Post-bind socket noise must not take the app or the monitor down.
      candidate.on('error', (error) => { lastServerError = safeString(error.message, 240, 'Socket error.'); });
    }
  } catch (error) {
    closeServer(candidate);
    pendingServer = null;
    if (version === lifecycleVersion) {
      lastServerError = safeString(
        error instanceof Error ? error.message : String(error),
        300,
        'The mobile monitor could not start.',
      );
    }
  } finally {
    if (starting === task) starting = null;
  }

  return mobileStatus();
}

/** Stop accepting requests and destroy keep-alive sockets immediately. */
export function stopMobileMonitor(): void {
  lifecycleVersion++;
  closeServer(pendingServer);
  pendingServer = null;
  closeServer(server);
  server = null;
  serverPort = null;
  for (const socket of sockets) {
    try { socket.destroy(); } catch { /* already closed */ }
  }
  sockets.clear();
}
