<?php

/**
 * @file
 * French for the words the theme prints and for the views' titles and
 * labels (configuration translations).
 */

return [
  'strings' => [
    'Ships free' => 'Livraison offerte',
    'Free shipping over $@amount' => 'Livraison offerte dès @amount $',
    'Add to basket' => 'Ajouter au panier',
    'Save for later' => 'Garder pour plus tard',
    'Price' => 'Prix',
    'Was' => 'Avant',
    'Menu' => 'Menu',
    'Close' => 'Fermer',
    'Pictures of @name' => 'Photos de @name',
    'Show picture @n' => 'Voir la photo @n',
    'Description' => 'Description',
    'Materials and care' => 'Matières et entretien',
    'Details' => 'Détails',
    'By' => 'Par',
    'min read' => 'min de lecture',
    'Highlights' => 'Points forts',
    'Pairs well with' => 'Va bien avec',
    'Search' => 'Rechercher',
    'Home' => 'Accueil',
    'Read more' => 'Lire la suite',
    'A made-up shop for Wanigan’s demo. Nothing here is for sale.' => 'Une boutique inventée pour la démo de Wanigan. Rien n’est à vendre.',
    'Skip to main content' => 'Aller au contenu principal',
    'Open the @name menu' => 'Ouvrir le menu @name',
    'All of @name' => 'Tout @name',
    'Welcome back, @name' => 'Bon retour, @name',
    "1 min read\x03@count min read" => "1 min de lecture\x03@count min de lecture",
    'From the shop' => 'Dans la boutique',
    'Journal' => 'Journal',
    'Open days' => 'Portes ouvertes',
    'Chosen for it' => 'Choisi pour lui',
    'Shipping' => 'Livraison',
    'Goods for long days outside, made a few at a time near the lake.' => 'Des objets pour les longues journées dehors, fabriqués en petites séries près du lac.',
    'This one ships free, and comes back free for a season.' => 'Livraison offerte, et retour gratuit pendant une saison.',
    'Free shipping on orders over $@amount, and free returns for a season.' => 'Livraison offerte dès @amount $, et retours gratuits pendant une saison.',
    'We pack orders on Thursdays and Fridays; most arrive within a week.' => 'Nous préparons les commandes le jeudi et le vendredi ; la plupart arrivent en une semaine.',
    'Pagination' => 'Pagination',
    'Breadcrumb' => 'Fil d’Ariane',
    'August|Long month name' => 'août',
    'September|Long month name' => 'septembre',
    'October|Long month name' => 'octobre',
    'November|Long month name' => 'novembre',
    'December|Long month name' => 'décembre',
    'Oct|Abbreviated month name' => 'oct.',
    'Nov|Abbreviated month name' => 'nov.',
    'Dec|Abbreviated month name' => 'déc.',
  ],
  'config' => [
    'system.site' => ['slogan' => 'Des objets pour les longues journées dehors'],
    'views.view.products' => [
      'display.default.display_options.title' => 'Boutique',
      'display.default.display_options.filters.field_category_target_id.expose.label' => 'Catégorie',
      'display.default.display_options.filters.field_price_value.expose.label' => 'Prix, $',
      'display.default.display_options.exposed_form.options.submit_button' => 'Afficher',
      'display.default.display_options.exposed_form.options.exposed_sorts_label' => 'Trier par',
      'display.default.display_options.sorts.created.expose.label' => 'Nouveautés',
      'display.default.display_options.sorts.field_price_value.expose.label' => 'Prix croissant',
      'display.default.display_options.sorts.field_price_value_1.expose.label' => 'Prix décroissant',
      'display.default.display_options.sorts.title.expose.label' => 'Nom',
      'display.default.display_options.header.result.content' => '@start–@end sur @total',
      'display.block_1.display_options.title' => 'Les meilleures ventes du mois',
      'display.block_1.display_options.footer.area_text_custom.content' => '<p><a class="button button--secondary" href="/fr/shop">Toute la boutique <span aria-hidden="true">→</span></a></p>',
      'display.block_2.display_options.title' => 'Dans la boutique',
      'display.block_3.display_options.title' => 'Dans le même esprit',
    ],
    'views.view.journal' => [
      'display.default.display_options.title' => 'Journal',
      'display.default.display_options.filters.field_tags_target_id.expose.label' => 'Sujet',
      'display.default.display_options.exposed_form.options.submit_button' => 'Afficher',
      'display.block_1.display_options.title' => 'Dans le journal',
      'display.block_1.display_options.footer.area_text_custom.content' => '<p><a class="button button--secondary" href="/fr/journal">Lire le journal <span aria-hidden="true">→</span></a></p>',
    ],
    'field.storage.node.field_badges' => [
      'settings.allowed_values.0.label' => 'Nouveau',
      'settings.allowed_values.1.label' => 'Meilleure vente',
      'settings.allowed_values.2.label' => 'Série limitée',
      'settings.allowed_values.3.label' => 'Matières recyclées',
    ],
    'block.block.northstar_footer_about' => ['settings.label' => 'À propos de Northstar'],
    'block.block.northstar_footer_menu' => ['settings.label' => 'Aide'],
    'block.block.northstar_footer_letters' => ['settings.label' => 'Lettres du lac'],
    'block.block.northstar_shop_the_story' => ['settings.label' => 'Dans la boutique'],
    'block.block.northstar_related' => ['settings.label' => 'Dans le même esprit'],
    'views.view.events' => [
      'display.default.display_options.title' => 'Portes ouvertes',
      'display.block_1.display_options.title' => 'Venez nous voir',
    ],
  ],
];
