<?php

/**
 * @file
 * Northstar's sixteen products, in English and French. Made up, every word:
 * names, places, prices and item numbers.
 *
 * Keys: slug (also the pictures' names), title, price, was (an earlier
 * price, for a sale), category, materials, badges, featured (promoted to the
 * front page), since (in the shop since), sku, highlights, body, care,
 * related (slugs), fr (title, highlights, body).
 */

return [
  [
    'slug' => 'lakeside-enamel-mug',
    'title' => 'Lakeside Enamel Mug',
    'price' => '24.00',
    'category' => 'Drinkware',
    'materials' => ['Enamelled steel'],
    'badges' => ['bestseller'],
    'featured' => TRUE,
    'since' => '2024-05-02',
    'sku' => 'NS-DW-001',
    'alt' => 'A pine-green enamel mug with the Northstar mark',
    'highlights' => ['Holds 12 oz, with room for milk', 'Steel core, glass enamel, rolled rim', 'Goes on the camp stove and in the dishwasher'],
    'body' => '<p>The mug we reach for first. Steel, dipped twice in pine-green enamel and fired, so it shrugs off a drop onto the dock and keeps coffee warm through the first chapter.</p><p>The rim is rolled and left bare. It will mark with use, which is how you can tell it has been somewhere.</p>',
    'care' => '<p>Dishwasher safe. Safe on a gas or camp stove; never heat it empty. A chip on the outside is cosmetic.</p>',
    'related' => ['ember-camp-mug', 'dawn-enamel-mug', 'field-journal'],
    'fr' => [
      'title' => 'Tasse émaillée Lakeside',
      'highlights' => ['Contient 35 cl, avec de la place pour le lait', 'Cœur en acier, émail vitrifié, bord roulé', 'Va sur le réchaud et au lave-vaisselle'],
      'body' => '<p>La tasse qu’on attrape en premier. De l’acier trempé deux fois dans un émail vert sapin, qui ne craint pas une chute sur le ponton et garde le café chaud pendant le premier chapitre.</p>',
    ],
  ],
  [
    'slug' => 'ember-camp-mug',
    'title' => 'Ember Camp Mug',
    'price' => '22.00',
    'category' => 'Drinkware',
    'materials' => ['Enamelled steel'],
    'badges' => ['new'],
    'featured' => FALSE,
    'since' => '2026-09-01',
    'sku' => 'NS-DW-002',
    'alt' => 'A speckled ember-orange enamel camp mug',
    'highlights' => ['Holds 10 oz', 'Hand-speckled, so no two match', 'Nests inside the Lakeside mug'],
    'body' => '<p>A smaller mug in ember orange, speckled by hand with a stiff brush before firing. It nests inside the Lakeside mug, so two pack in the space of one.</p>',
    'care' => '<p>Dishwasher safe. The speckles are part of the glaze and will not wear off.</p>',
    'related' => ['lakeside-enamel-mug', 'harbor-camp-lantern', 'trail-bottle'],
    // A change waiting for review: a newer draft revision over the published one.
    'draft' => [
      'price' => '20.00',
      'body' => '<p>A smaller mug in ember orange, speckled by hand with a stiff brush before firing. It nests inside the Lakeside mug, so two pack in the space of one.</p><p>Now also sold as a pair, for the price of a mug and a half.</p>',
      'log' => 'Sam: lower price for autumn, mention the pair',
    ],
    'fr' => [
      'title' => 'Tasse de camp Ember',
      'highlights' => ['Contient 30 cl', 'Mouchetée à la main : aucune n’est pareille', 'Se range dans la tasse Lakeside'],
      'body' => '<p>Une tasse plus petite, orange braise, mouchetée à la brosse avant cuisson. Elle se range dans la tasse Lakeside : deux tasses dans la place d’une.</p>',
    ],
  ],
  [
    'slug' => 'dawn-enamel-mug',
    'title' => 'Dawn Enamel Mug',
    'price' => '24.00',
    'category' => 'Drinkware',
    'materials' => ['Enamelled steel'],
    'badges' => [],
    'featured' => FALSE,
    'since' => '2025-03-14',
    'sku' => 'NS-DW-003',
    'alt' => 'A sand-coloured speckled enamel mug',
    'highlights' => ['Holds 12 oz', 'The colour of the shore at six in the morning', 'Steel core, glass enamel, rolled rim'],
    'body' => '<p>The Lakeside mug in the pale sand of a beach before the sun is on it, with a dark speckle like wet stones. Same weight, same handle, same rolled rim.</p>',
    'care' => '<p>Dishwasher safe. Safe on a gas or camp stove; never heat it empty.</p>',
    'related' => ['lakeside-enamel-mug', 'ember-camp-mug', 'night-field-journal'],
    'fr' => [
      'title' => 'Tasse émaillée Aube',
      'highlights' => ['Contient 35 cl', 'La couleur de la rive à six heures du matin', 'Cœur en acier, émail vitrifié, bord roulé'],
      'body' => '<p>La tasse Lakeside dans le sable pâle d’une plage avant le soleil, mouchetée de sombre comme des galets mouillés.</p>',
    ],
  ],
  [
    'slug' => 'trail-bottle',
    'title' => 'Trail Bottle, 750 ml',
    'price' => '38.00',
    'category' => 'Drinkware',
    'materials' => ['Stainless steel'],
    'badges' => ['recycled'],
    'featured' => FALSE,
    'since' => '2025-06-20',
    'sku' => 'NS-DW-004',
    'alt' => 'A tall lake-blue insulated bottle with a cream label',
    'highlights' => ['Keeps water cold for a day, tea hot till lunch', '80% recycled stainless steel', 'Loop cap you can hang from a pack'],
    'body' => '<p>Double-walled and quiet: no rattle, no sweat on the outside, no taste of last week\'s soup. The loop cap clips to a pack strap or a canoe thwart.</p>',
    'care' => '<p>Hand wash. Leave the cap off to dry. Not for the freezer.</p>',
    'related' => ['rolltop-day-pack', 'lakeside-enamel-mug', 'waxed-field-cap'],
    'fr' => [
      'title' => 'Gourde Trail, 75 cl',
      'highlights' => ['L’eau reste fraîche une journée, le thé chaud jusqu’à midi', 'Acier inoxydable recyclé à 80 %', 'Bouchon à anse, à accrocher au sac'],
      'body' => '<p>Double paroi et silencieuse : pas de cliquetis, pas de condensation, pas de goût de la soupe de la semaine dernière.</p>',
    ],
  ],
  [
    'slug' => 'canvas-market-tote',
    'title' => 'Canvas Market Tote',
    'price' => '32.00',
    'category' => 'Bags',
    'materials' => ['Cotton canvas', 'Leather'],
    'badges' => ['recycled', 'bestseller'],
    'featured' => TRUE,
    'since' => '2024-04-11',
    'sku' => 'NS-BG-001',
    'alt' => 'A natural canvas tote bag printed with a green mountain mark',
    'highlights' => ['Heavy 14 oz canvas from recycled cotton', 'Leather-wrapped handles', 'Folds flat into a coat pocket'],
    'body' => '<p>Big enough for a week of groceries or a wet towel and a paperback. The canvas starts stiff and softens over a summer; the print is water-based and fades slowly, like a good sign.</p>',
    'care' => '<p>Cold wash inside out, line dry. The leather handles darken with use.</p>',
    'related' => ['ember-market-tote', 'rolltop-day-pack', 'lakehouse-wool-blanket'],
    'fr' => [
      'title' => 'Cabas en toile Market',
      'highlights' => ['Toile épaisse de coton recyclé', 'Anses gainées de cuir', 'Se plie dans une poche de manteau'],
      'body' => '<p>Assez grand pour une semaine de courses, ou une serviette mouillée et un livre de poche. La toile s’assouplit au fil de l’été.</p>',
    ],
  ],
  [
    'slug' => 'ember-market-tote',
    'title' => 'Market Tote, Ember',
    'price' => '28.00',
    'was' => '34.00',
    'category' => 'Bags',
    'materials' => ['Cotton canvas'],
    'badges' => ['limited'],
    'featured' => FALSE,
    'since' => '2025-10-01',
    'sku' => 'NS-BG-002',
    'alt' => 'An ember-red canvas tote with a cream mountain print',
    'highlights' => ['Dyed ember red, printed in cream', 'The same heavy canvas as the natural tote', 'Last of this year\'s dye lot'],
    'body' => '<p>The market tote dyed the colour of a campfire\'s last coals and printed in cream. One dye lot a year, and this is the end of it.</p>',
    'care' => '<p>Cold wash alone the first time; the dye may run a little.</p>',
    'related' => ['canvas-market-tote', 'ridge-wool-beanie', 'ember-camp-mug'],
    'fr' => [
      'title' => 'Cabas Market, Braise',
      'highlights' => ['Teint rouge braise, imprimé crème', 'La même toile épaisse que le cabas naturel', 'La fin du bain de teinture de l’année'],
      'body' => '<p>Le cabas teint de la couleur des dernières braises d’un feu de camp, imprimé crème. Un seul bain par an, et c’est la fin.</p>',
    ],
  ],
  [
    'slug' => 'rolltop-day-pack',
    'title' => 'Roll-top Day Pack',
    'price' => '89.00',
    'category' => 'Bags',
    'materials' => ['Waxed canvas'],
    'badges' => ['new'],
    'featured' => TRUE,
    'since' => '2026-08-15',
    'sku' => 'NS-BG-003',
    'alt' => 'An ember-red roll-top backpack with a yellow strap',
    'highlights' => ['22 litres, rolls down to 16', 'Waxed canvas body, welded waterproof liner', 'Padded sleeve fits a 15-inch laptop'],
    'body' => '<p>One big room, one front pocket, nothing to lose. Roll the top three times and it keeps a downpour out of your lunch; roll it once and it holds a jacket too.</p>',
    'care' => '<p>Brush off dried mud, wipe with cold water, re-wax once a year. Never machine wash.</p>',
    'related' => ['trail-bottle', 'canvas-market-tote', 'waxed-field-cap'],
    'fr' => [
      'title' => 'Sac à dos à rabat roulé',
      'highlights' => ['22 litres, se roule jusqu’à 16', 'Toile cirée, doublure étanche soudée', 'Poche matelassée pour un portable de 15 pouces'],
      'body' => '<p>Un grand compartiment, une poche devant, rien à perdre. Roulez le haut trois fois et l’averse reste dehors.</p>',
    ],
  ],
  [
    'slug' => 'silverpine-lake-map',
    'title' => 'Silverpine Lake Map Print',
    'price' => '45.00',
    'category' => 'Prints',
    'materials' => ['Cotton rag paper'],
    'badges' => ['limited'],
    'featured' => TRUE,
    'since' => '2025-02-01',
    'sku' => 'NS-PR-001',
    'alt' => 'A framed hand-drawn depth map of a lake in blues and greens',
    'highlights' => ['Drawn by hand from an old depth survey', 'Giclée print on cotton rag paper, 12 × 16 in', 'Run of 200, signed and numbered'],
    'body' => '<p>Silverpine is a lake we made up and then got to know: a deep north basin, a shallow bay full of reeds, and three islands that look different every time we draw them.</p><p>Printed on heavy cotton paper and shipped flat between boards. The frame in the picture is not included.</p>',
    'care' => '<p>Frame behind UV glass and keep out of direct sun.</p>',
    'related' => ['northern-sky-star-chart', 'field-journal', 'lakehouse-wool-blanket'],
    'fr' => [
      'title' => 'Carte du lac Silverpine',
      'highlights' => ['Dessinée à la main d’après un vieux relevé', 'Impression giclée sur papier chiffon, 30 × 40 cm', 'Tirage de 200, signé et numéroté'],
      'body' => '<p>Silverpine est un lac inventé que nous avons appris à connaître : une fosse profonde au nord, une baie de roseaux et trois îles qui changent à chaque dessin.</p>',
    ],
  ],
  [
    'slug' => 'northern-sky-star-chart',
    'title' => 'Northern Sky Star Chart',
    'price' => '40.00',
    'category' => 'Prints',
    'materials' => ['Cotton rag paper'],
    'badges' => [],
    'featured' => FALSE,
    'since' => '2025-08-20',
    'sku' => 'NS-PR-002',
    'alt' => 'A framed navy star chart with the Big Dipper in gold',
    'highlights' => ['The sky at midnight in late August', 'Gold ink on navy, 12 × 16 in', 'Ships flat between boards'],
    'body' => '<p>The sky as it looks from a dark shore at midnight in late August: the Dipper low in the north, and the bright star it points to.</p>',
    'care' => '<p>Frame behind UV glass and keep out of direct sun.</p>',
    'related' => ['silverpine-lake-map', 'harbor-camp-lantern', 'night-field-journal'],
    'fr' => [
      'title' => 'Carte du ciel boréal',
      'highlights' => ['Le ciel à minuit fin août', 'Encre dorée sur bleu nuit, 30 × 40 cm', 'Expédiée à plat entre deux cartons'],
      'body' => '<p>Le ciel vu d’une rive sombre à minuit fin août : la Grande Ourse basse au nord, et l’étoile qu’elle désigne.</p>',
    ],
  ],
  [
    'slug' => 'waxed-field-cap',
    'title' => 'Waxed Field Cap',
    'price' => '28.00',
    'category' => 'Apparel',
    'materials' => ['Waxed canvas'],
    'badges' => ['bestseller'],
    'featured' => FALSE,
    'since' => '2024-09-05',
    'sku' => 'NS-AP-001',
    'alt' => 'A brown waxed-canvas cap with a cream mountain patch',
    'highlights' => ['Waxed cotton canvas sheds a shower', 'Brass buckle, one size fits most', 'Re-wax it every spring'],
    'body' => '<p>A low six-panel cap in waxed canvas the colour of wet bark. It darkens where your hands hold the brim, and a tin of wax brings it back each spring.</p>',
    'care' => '<p>Spot clean with cold water. Re-wax with a warm cloth once a year.</p>',
    'related' => ['ridge-wool-beanie', 'storm-wool-beanie', 'rolltop-day-pack'],
    'fr' => [
      'title' => 'Casquette en toile cirée',
      'highlights' => ['La toile cirée laisse glisser l’averse', 'Boucle en laiton, taille unique', 'À recirer chaque printemps'],
      'body' => '<p>Une casquette basse à six pans en toile cirée couleur d’écorce mouillée. Elle fonce là où vos mains tiennent la visière.</p>',
    ],
  ],
  [
    'slug' => 'ridge-wool-beanie',
    'title' => 'Ridge Wool Beanie',
    'price' => '26.00',
    'category' => 'Apparel',
    'materials' => ['Recycled wool'],
    'badges' => ['recycled'],
    'featured' => FALSE,
    'since' => '2024-10-15',
    'sku' => 'NS-AP-002',
    'alt' => 'A rust-red ribbed wool beanie with a cream stripe and pom-pom',
    'highlights' => ['Knit from recycled wool', 'Deep cuff folds over the ears', 'Hand wash cold, dry flat'],
    'body' => '<p>Rust red with one cream stripe, knit from wool that had a life as a sweater first. The cuff is deep enough to fold over your ears when the wind turns.</p>',
    'care' => '<p>Hand wash cold, dry flat away from the stove.</p>',
    'related' => ['storm-wool-beanie', 'waxed-field-cap', 'lakehouse-wool-blanket'],
    'fr' => [
      'title' => 'Bonnet en laine Ridge',
      'highlights' => ['Tricoté en laine recyclée', 'Revers profond qui couvre les oreilles', 'Lavage à froid, séchage à plat'],
      'body' => '<p>Rouille avec une rayure crème, tricoté dans une laine qui a d’abord été un pull.</p>',
    ],
  ],
  [
    'slug' => 'storm-wool-beanie',
    'title' => 'Storm Wool Beanie',
    'price' => '26.00',
    'category' => 'Apparel',
    'materials' => ['Recycled wool'],
    'badges' => ['new', 'recycled'],
    'featured' => FALSE,
    'since' => '2026-09-20',
    'sku' => 'NS-AP-003',
    'alt' => 'A storm-blue ribbed wool beanie with a gold stripe',
    'highlights' => ['Storm blue with a gold stripe', 'Knit from recycled wool', 'Deep cuff folds over the ears'],
    'body' => '<p>The Ridge beanie in the blue-grey of a squall coming down the lake, with a gold stripe so you can find it in the bottom of the bag.</p>',
    'care' => '<p>Hand wash cold, dry flat away from the stove.</p>',
    'related' => ['ridge-wool-beanie', 'waxed-field-cap', 'trail-bottle'],
    'fr' => [
      'title' => 'Bonnet en laine Orage',
      'highlights' => ['Bleu orage, rayure dorée', 'Tricoté en laine recyclée', 'Revers profond qui couvre les oreilles'],
      'body' => '<p>Le bonnet Ridge dans le bleu-gris d’un grain qui descend sur le lac, avec une rayure dorée pour le retrouver au fond du sac.</p>',
    ],
  ],
  [
    'slug' => 'field-journal',
    'title' => 'Field Journal, Dot Grid',
    'price' => '18.00',
    'category' => 'Paper goods',
    'materials' => ['Cotton rag paper'],
    'badges' => ['bestseller'],
    'featured' => FALSE,
    'since' => '2024-03-01',
    'sku' => 'NS-PG-001',
    'alt' => 'A pine-green cloth notebook with an elastic band and red ribbon',
    'highlights' => ['192 pages of 100 gsm dot grid', 'Lies flat, takes fountain pen ink', 'Elastic band and a ribbon marker'],
    'body' => '<p>For bird counts, packing lists and the name of that one campsite. The cloth cover takes a beating, the paper takes ink without bleeding, and the ribbon keeps your place.</p>',
    'care' => '<p>Keep it dry, or at least dry it flat under a book.</p>',
    'related' => ['night-field-journal', 'silverpine-lake-map', 'lakeside-enamel-mug'],
    'fr' => [
      'title' => 'Carnet de terrain, pointillés',
      'highlights' => ['192 pages de 100 g à pointillés', 'S’ouvre à plat, accepte l’encre de stylo-plume', 'Élastique et signet en ruban'],
      'body' => '<p>Pour compter les oiseaux, lister les affaires et noter le nom de ce bivouac. La couverture en toile encaisse, le papier boit l’encre sans baver.</p>',
    ],
  ],
  [
    'slug' => 'night-field-journal',
    'title' => 'Field Journal, Night',
    'price' => '18.00',
    'category' => 'Paper goods',
    'materials' => ['Cotton rag paper'],
    'badges' => ['new'],
    'featured' => FALSE,
    'since' => '2026-09-10',
    'sku' => 'NS-PG-002',
    'alt' => 'A navy cloth notebook with an elastic band and red ribbon',
    'highlights' => ['Navy cloth cover', '192 pages of 100 gsm dot grid', 'Elastic band and a ribbon marker'],
    'body' => '<p>The field journal in a navy cloth, for the notes you write by headlamp: star counts, owl calls, the time the loons started.</p>',
    'care' => '<p>Keep it dry, or at least dry it flat under a book.</p>',
    'related' => ['field-journal', 'northern-sky-star-chart', 'harbor-camp-lantern'],
    'fr' => [
      'title' => 'Carnet de terrain, Nuit',
      'highlights' => ['Couverture en toile bleu nuit', '192 pages de 100 g à pointillés', 'Élastique et signet en ruban'],
      'body' => '<p>Le carnet de terrain en toile bleu nuit, pour les notes prises à la frontale : étoiles, hiboux, l’heure où les plongeons ont commencé.</p>',
    ],
  ],
  [
    'slug' => 'harbor-camp-lantern',
    'title' => 'Harbor Camp Lantern',
    'price' => '54.00',
    'category' => 'Camp',
    'materials' => ['Stainless steel', 'Glass'],
    'badges' => ['new'],
    'featured' => FALSE,
    'since' => '2026-07-01',
    'sku' => 'NS-CA-001',
    'alt' => 'A lake-blue camp lantern glowing warm yellow',
    'highlights' => ['Warm light, three brightness steps', 'Charges by USB-C, runs 40 hours on low', 'Wire handle hangs from a branch or a tent loop'],
    'body' => '<p>A lantern that looks like the old kind and charges like a phone. On low it reads like candlelight and lasts a long weekend; on high it finds the tent pegs you dropped.</p>',
    'care' => '<p>Splash-proof, not waterproof. Charge it fully before storing it for winter.</p>',
    'related' => ['ember-camp-mug', 'lakehouse-wool-blanket', 'northern-sky-star-chart'],
    'fr' => [
      'title' => 'Lanterne de camp Harbor',
      'highlights' => ['Lumière chaude, trois intensités', 'Recharge USB-C, 40 heures en veilleuse', 'Anse en fil pour l’accrocher à une branche'],
      'body' => '<p>Une lanterne qui ressemble aux anciennes et se recharge comme un téléphone. En veilleuse, on dirait une bougie.</p>',
    ],
  ],
  [
    'slug' => 'lakehouse-wool-blanket',
    'title' => 'Lakehouse Wool Blanket',
    'price' => '120.00',
    'was' => '140.00',
    'category' => 'Camp',
    'materials' => ['Recycled wool'],
    'badges' => ['limited'],
    'featured' => FALSE,
    'since' => '2025-11-01',
    'sku' => 'NS-CA-002',
    'alt' => 'A folded cream wool blanket with red, gold and green stripes',
    'highlights' => ['Pure wool, woven in a small mill', '60 × 80 in, fringed ends', 'Stripes in ember, gold and pine'],
    'body' => '<p>The blanket for the porch, the canoe bottom and the back seat. Cream wool with three stripes, heavy enough to keep the wind off and soft enough to sleep under.</p>',
    'care' => '<p>Air it outside after a trip. Dry clean, or hand wash cold in a bath and dry flat.</p>',
    'related' => ['harbor-camp-lantern', 'canvas-market-tote', 'ridge-wool-beanie'],
    'fr' => [
      'title' => 'Couverture en laine Lakehouse',
      'highlights' => ['Pure laine, tissée dans une petite filature', '150 × 200 cm, franges', 'Rayures braise, or et sapin'],
      'body' => '<p>La couverture du porche, du fond du canoë et de la banquette arrière. Laine crème à trois rayures, assez lourde contre le vent.</p>',
    ],
  ],
];
