<?php

/**
 * @file
 * Northstar's twelve products. Made up, every word: names, places and prices.
 */

return [
  [
    'slug' => 'lakeside-enamel-mug',
    'title' => 'Lakeside Enamel Mug',
    'price' => '24.00',
    'category' => 'Drinkware',
    'badges' => ['bestseller'],
    'featured' => TRUE,
    'alt' => 'A pine-green enamel mug with the Northstar mark',
    'highlights' => ['Holds 12 oz, with room for milk', 'Steel core, glass enamel, rolled rim', 'Goes on the camp stove and in the dishwasher'],
    'body' => '<p>The mug we reach for first. Steel, dipped twice in pine-green enamel and fired, so it shrugs off a drop onto the dock and keeps coffee warm through the first chapter.</p><p>The rim is rolled and left bare. It will mark with use, which is how you can tell it has been somewhere.</p>',
    'related' => ['ember-camp-mug', 'trail-bottle', 'field-journal'],
  ],
  [
    'slug' => 'ember-camp-mug',
    'title' => 'Ember Camp Mug',
    'price' => '22.00',
    'category' => 'Drinkware',
    'badges' => ['new'],
    'featured' => FALSE,
    'alt' => 'A speckled ember-orange enamel camp mug',
    'highlights' => ['Holds 10 oz', 'Hand-speckled, so no two match', 'Nests inside the Lakeside mug'],
    'body' => '<p>A smaller mug in ember orange, speckled by hand with a stiff brush before firing. It nests inside the Lakeside mug, so two pack in the space of one.</p>',
    'related' => ['lakeside-enamel-mug', 'harbor-camp-lantern', 'trail-bottle'],
  ],
  [
    'slug' => 'trail-bottle',
    'title' => 'Trail Bottle, 750 ml',
    'price' => '38.00',
    'category' => 'Drinkware',
    'badges' => ['recycled'],
    'featured' => FALSE,
    'alt' => 'A tall lake-blue insulated bottle with a cream label',
    'highlights' => ['Keeps water cold for a day, tea hot till lunch', '80% recycled stainless steel', 'Loop cap you can hang from a pack'],
    'body' => '<p>Double-walled and quiet: no rattle, no sweat on the outside, no taste of last week\'s soup. The loop cap clips to a pack strap or a canoe thwart.</p>',
    'related' => ['rolltop-day-pack', 'lakeside-enamel-mug', 'waxed-field-cap'],
  ],
  [
    'slug' => 'canvas-market-tote',
    'title' => 'Canvas Market Tote',
    'price' => '32.00',
    'category' => 'Bags',
    'badges' => ['recycled', 'bestseller'],
    'featured' => TRUE,
    'alt' => 'A natural canvas tote bag printed with a green mountain mark',
    'highlights' => ['Heavy 14 oz canvas from recycled cotton', 'Leather-wrapped handles', 'Folds flat into a coat pocket'],
    'body' => '<p>Big enough for a week of groceries or a wet towel and a paperback. The canvas starts stiff and softens over a summer; the print is water-based and fades slowly, like a good sign.</p>',
    'related' => ['rolltop-day-pack', 'field-journal', 'lakehouse-wool-blanket'],
  ],
  [
    'slug' => 'rolltop-day-pack',
    'title' => 'Roll-top Day Pack',
    'price' => '89.00',
    'category' => 'Bags',
    'badges' => ['new'],
    'featured' => TRUE,
    'alt' => 'An ember-red roll-top backpack with a yellow strap',
    'highlights' => ['22 litres, rolls down to 16', 'Waxed canvas body, welded waterproof liner', 'Padded sleeve fits a 15-inch laptop'],
    'body' => '<p>One big room, one front pocket, nothing to lose. Roll the top three times and it keeps a downpour out of your lunch; roll it once and it holds a jacket too.</p>',
    'related' => ['trail-bottle', 'canvas-market-tote', 'waxed-field-cap'],
  ],
  [
    'slug' => 'silverpine-lake-map',
    'title' => 'Silverpine Lake Map Print',
    'price' => '45.00',
    'category' => 'Prints',
    'badges' => ['limited'],
    'featured' => TRUE,
    'alt' => 'A framed hand-drawn depth map of a lake in blues and greens',
    'highlights' => ['Drawn by hand from an old depth survey', 'Giclée print on cotton rag paper, 12 × 16 in', 'Run of 200, signed and numbered'],
    'body' => '<p>Silverpine is a lake we made up and then got to know: a deep north basin, a shallow bay full of reeds, and three islands that look different every time we draw them.</p><p>Printed on heavy cotton paper and shipped flat between boards. The frame in the picture is not included.</p>',
    'related' => ['northern-sky-star-chart', 'field-journal', 'lakehouse-wool-blanket'],
  ],
  [
    'slug' => 'northern-sky-star-chart',
    'title' => 'Northern Sky Star Chart',
    'price' => '40.00',
    'category' => 'Prints',
    'badges' => [],
    'featured' => FALSE,
    'alt' => 'A framed navy star chart with the Big Dipper in gold',
    'highlights' => ['The sky at midnight in late August', 'Gold ink on navy, 12 × 16 in', 'Ships flat between boards'],
    'body' => '<p>The sky as it looks from a dark shore at midnight in late August: the Dipper low in the north, and the bright star it points to.</p>',
    'related' => ['silverpine-lake-map', 'harbor-camp-lantern', 'lakehouse-wool-blanket'],
  ],
  [
    'slug' => 'waxed-field-cap',
    'title' => 'Waxed Field Cap',
    'price' => '28.00',
    'category' => 'Apparel',
    'badges' => ['bestseller'],
    'featured' => FALSE,
    'alt' => 'A brown waxed-canvas cap with a cream mountain patch',
    'highlights' => ['Waxed cotton canvas sheds a shower', 'Brass buckle, one size fits most', 'Re-wax it every spring'],
    'body' => '<p>A low six-panel cap in waxed canvas the colour of wet bark. It darkens where your hands hold the brim, and a tin of wax brings it back each spring.</p>',
    'related' => ['ridge-wool-beanie', 'rolltop-day-pack', 'trail-bottle'],
  ],
  [
    'slug' => 'ridge-wool-beanie',
    'title' => 'Ridge Wool Beanie',
    'price' => '26.00',
    'category' => 'Apparel',
    'badges' => ['recycled'],
    'featured' => FALSE,
    'alt' => 'A rust-red ribbed wool beanie with a cream stripe and pom-pom',
    'highlights' => ['Knit from recycled wool', 'Deep cuff folds over the ears', 'Hand wash cold, dry flat'],
    'body' => '<p>Rust red with one cream stripe, knit from wool that had a life as a sweater first. The cuff is deep enough to fold over your ears when the wind turns.</p>',
    'related' => ['waxed-field-cap', 'lakehouse-wool-blanket', 'ember-camp-mug'],
  ],
  [
    'slug' => 'field-journal',
    'title' => 'Field Journal, Dot Grid',
    'price' => '18.00',
    'category' => 'Paper goods',
    'badges' => ['bestseller'],
    'featured' => FALSE,
    'alt' => 'A pine-green cloth notebook with an elastic band and red ribbon',
    'highlights' => ['192 pages of 100 gsm dot grid', 'Lies flat, takes fountain pen ink', 'Elastic band and a ribbon marker'],
    'body' => '<p>For bird counts, packing lists and the name of that one campsite. The cloth cover takes a beating, the paper takes ink without bleeding, and the ribbon keeps your place.</p>',
    'related' => ['silverpine-lake-map', 'canvas-market-tote', 'lakeside-enamel-mug'],
  ],
  [
    'slug' => 'harbor-camp-lantern',
    'title' => 'Harbor Camp Lantern',
    'price' => '54.00',
    'category' => 'Camp',
    'badges' => ['new'],
    'featured' => FALSE,
    'alt' => 'A lake-blue camp lantern glowing warm yellow',
    'highlights' => ['Warm light, three brightness steps', 'Charges by USB-C, runs 40 hours on low', 'Wire handle hangs from a branch or a tent loop'],
    'body' => '<p>A lantern that looks like the old kind and charges like a phone. On low it reads like candlelight and lasts a long weekend; on high it finds the tent pegs you dropped.</p>',
    'related' => ['ember-camp-mug', 'lakehouse-wool-blanket', 'northern-sky-star-chart'],
  ],
  [
    'slug' => 'lakehouse-wool-blanket',
    'title' => 'Lakehouse Wool Blanket',
    'price' => '120.00',
    'category' => 'Camp',
    'badges' => ['limited'],
    'featured' => FALSE,
    'alt' => 'A folded cream wool blanket with red, gold and green stripes',
    'highlights' => ['Pure wool, woven in a small mill', '60 × 80 in, fringed ends', 'Stripes in ember, gold and pine'],
    'body' => '<p>The blanket for the porch, the canoe bottom and the back seat. Cream wool with three stripes, heavy enough to keep the wind off and soft enough to sleep under.</p>',
    'related' => ['harbor-camp-lantern', 'canvas-market-tote', 'ridge-wool-beanie'],
  ],
];
